README.md, cd-tekton-pipeline/v2.ts, examples/cd-tekton-pipeline.v2.test.js, package-lock.json, package.json, test/integration/cd-tekton-pipeline.v2.test.js, test/unit/cd-tekton-pipeline.v2.test.js
Updated SDK for tekton pipelines v2
Adjusted the required/computed state of some properties. Used a newer version of the sdk generator also, which has added some extra functions.
=> fix(update tekton sdk): Update the node sdk for tekton pipeline v2

.bumpversion.cfg, .travis.yml, README.md
=> chore(build): enable semantic versioning

package.json
=> chore(build): fix package json

.releaserc
=> chore(build): fix automatic sem ver

.bumpversion.cfg, README.md, cd-tekton-pipeline/v2.ts, examples/cd-tekton-pipeline.v2.test.js, package.json, test/integration/cd-tekton-pipeline.v2.test.js, test/unit/cd-tekton-pipeline.v2.test.js
- Reshape `resource_group_id` to `resource_group: { id: '[rgid]' }`
- Change `trigger.disabled` to `trigger.enabled`, to be consistent with `pipeline.enabled`
- For git triggers, reshaped `events` object into an array of strings, e.g. `events: ["pull", "pull_request"]
- Rename `enable_slack_notifications` to `enable_notifications`
- Rename `pipelineRun.agent` to `pipelineRun.agent_id`
- Moved call to `convertPropertyTypesForV2` into `preparePipelineDataForGetV2` function
- Better error handling in `event-service-client.js`
- Remove `id` from definition create request body, and fix associated code handling the request
- More specific regex patterns for a number of items
- Bump up `maxItems` count on some items now that generator bug for this was fixed
- Update `WorkerWithId` and …
=> fix(tekton): Update Tekton to match V2 API GA changes

cd-toolchain/v2.ts, test/unit/cd-toolchain.v2.test.js
Signed-off-by: Omar Al Bastami <omar.albastami@ibm.com>
Removed `tags` property from toolchain SDK
=> remove 'tags' from toolchain SDK

README.md, cd-tekton-pipeline/v2.ts, examples/cd-tekton-pipeline.v2.test.js, test/integration/cd-tekton-pipeline.v2.test.js, test/unit/cd-tekton-pipeline.v2.test.js
Remove offset option when fetching pipeline runs. And dont set a default value for booleans in PATCH requests
=> fix(tekton): remove offset and patch defaults

README.md, package-lock.json, package.json
Signed-off-by: Omar Al Bastami <omar.albastami@ibm.com>
=> docs: update package version to match latest

.cra/.cveignore, .travis.yml, README.md, cd-tekton-pipeline/v2.ts, examples/cd-tekton-pipeline.v2.test.js, package-lock.json, package.json, test/integration/cd-tekton-pipeline.v2.test.js, test/unit/cd-tekton-pipeline.v2.test.js
The supporting Tekton Pipeline V2 APIs have been udpated after their GA with some minor fixes/changes. Sync the node-sdk to match the updates
These API updates are not likely to be deployed to production until the new year (Jan 2023)
Furthermore, fix up the integration test for tekton pipeline
=> Tekton updates after the V2 API GA

README.md
Fix links in the readme and associated install paths
=> chore(doc): fix readme links

.bumpversion.cfg, README.md, package.json
Attempt to fix the publish problems in recent builds
=> fix(build): attempt to fix publish problem

.bumpversion.cfg, README.md, package.json
Clean up `releases` in package.json to attempt to fix semVer auto-update not taking place. See the notes here: https://semantic-release.gitbook.io/semantic-release/usage/configuration#configuration-file
=> fix(build): attempt fix of semVer issue

README.md
=> chore(doc): fix npm link in README

README.md
Update version numbers in the doc so that they match the latest release, as the doc appears in the npm registry release page
=> fix(doc): sync release version in docs

README.md
Attempt to fix version mismatch was not correct. Refixing to v0.2.11
=> fix(doc): version correction

README.md
BREAKING CHANGE: release v1.0.0
Release v1.0.0
=> feat(build): trigger major version build

cd-tekton-pipeline/v2.ts, test/unit/cd-tekton-pipeline.v2.test.js
Add support for `next_build_number` property in Tekton Pipelines
=> feat(tekton): add next build number support

package-lock.json, package.json
Upgraded ibm-core-sdk-core dependency version according to node SDK template repo
=> feat: upgrade ibm-core-sdk-core dependency version

.secrets.baseline
Dummy values in test/example files are being marked as false positives in detect-secrets script. Exclude them from the scans.
=> build: update secrets baseline

package-lock.json, package.json
Bump node core to 4.0.8, ran npm install
=> build: bump core dependency

package-lock.json, package.json
Update node core to version 4.1.0 as per template
=> build: bump node core to 4.1.0

cd-tekton-pipeline/v2.ts, examples/cd-tekton-pipeline.v2.test.js, test/unit/cd-tekton-pipeline.v2.test.js
Add support for favorite triggers in Tekton pipeline
Also includes some minor documentation updates
=> fix(tekton): add trigger favorite

.travis.yml
Fixes GPG errors in travis builds.
=> build: avoid GPG errors in travis builds

cd-toolchain/v2.ts, examples/cd-toolchain.v2.test.js, test/integration/cd-toolchain.v2.test.js, test/unit/cd-toolchain.v2.test.js
Supporting `name` parameter when retrieving toolchain collection
=> feat(toolchain): add name query param to list toolchains

.prettierrc.js, .travis.yml
=> fix: upgrade deploy node version

.secrets.baseline, cd-toolchain/v2.ts, examples/cd-toolchain.v2.test.js, test/integration/cd-toolchain.v2.test.js, test/unit/cd-toolchain.v2.test.js
=> feat(toolchain): add eu-es region

CHANGELOG.md, cd-tekton-pipeline/v2.ts, package-lock.json, package.json, test/unit/cd-tekton-pipeline.v2.test.js
=> feat(tekton): add eu-es region

.secrets.baseline, CHANGELOG.md, cd-tekton-pipeline/v2.ts, cd-toolchain/v2.ts, examples/cd-toolchain.v2.test.js, package-lock.json, package.json, test/integration/cd-toolchain.v2.test.js, test/unit/cd-tekton-pipeline.v2.test.js, test/unit/cd-toolchain.v2.test.js
=> feat: support eu-es region

.secrets.baseline, cd-toolchain/v2.ts, examples/cd-toolchain.v2.test.js, package-lock.json, package.json, test/integration/cd-toolchain.v2.test.js, test/unit/cd-toolchain.v2.test.js
Added function that invokes the create toolchain event API endpoint and added associated tests. Also updated SDK dependencies and versions.
=> feat(toolchain): add function to create toolchain event 

package-lock.json, package.json
- Update core-sdk to match template: https://github.ibm.com/CloudEngineering/node-sdk-template/pull/97
- Update nock version to address vuln in lodash.set: https://github.com/IBM/continuous-delivery-node-sdk/security/dependabot/24
=> fix: bump packages to address vulnerabilities

cd-tekton-pipeline/v2.ts, package-lock.json, package.json, test/unit/cd-tekton-pipeline.v2.test.js
Add support for locked properties in Tekton pipeline and triggers.
Also update some packages to address vulnerabilities
=> feat(tekton): Add locked property support

cd-tekton-pipeline/v2.ts, test/unit/cd-tekton-pipeline.v2.test.js
Add support for CEL filtering of Git triggers in tekton pipeline
=> feat(tekton): Add support for CEL filtering

cd-tekton-pipeline/v2.ts, examples/cd-tekton-pipeline.v2.test.js, test/unit/cd-tekton-pipeline.v2.test.js
https://github.ibm.com/org-ids/roadmap/issues/27538
Add PipelineRun description property
=> feat(tekton): add run description for pipeline runs

cd-tekton-pipeline/v2.ts
Add option to enable/disable fork events in git triggers
=> feat(tekton): Add fork events option

cd-tekton-pipeline/v2.ts, test/unit/cd-tekton-pipeline.v2.test.js
Add full support for the "enable events from forks" feature to Tekton Git triggers
=> feat(tekton): more fork support

tsconfig.json
Attempt to fix a Node20 build issue affecting recent builds: https://app.travis-ci.com/github/IBM/continuous-delivery-node-sdk/jobs/634188454
```
> postversion
> publisher --no-checks --dry-run
Failed to parse tsconfig.json file
npm error code 1
npm error path /home/travis/build/IBM/continuous-delivery-node-sdk/dist
npm error command failed
npm error command sh -c publisher --no-checks --dry-run
```
=> chore: fix Node20 build issue

cd-tekton-pipeline/v2.ts, test/unit/cd-tekton-pipeline.v2.test.js
Add support for the disable_draft_events option on Git triggers
=> fix: add draft PR events support
